spring:
  datasource:
    url: jdbc:mysql://10.70.7.244:3306/tianxun_user?useSSL=false
    username: root
    password: 3416763
    driver-class-name: com.mysql.jdbc.Driver
    # druid数据源配置
    druid:
      url: jdbc:mysql://10.70.7.244:3306/tianxun_user?useSSL=false
      username: root
      password: 3416763
      driver-class-name: com.mysql.jdbc.Driver
      # 连接池配置
      initial-size: 1
      max-active: 2
      min-idle: 1
      max-wait: 2
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      #max-open-prepared-statements= #和上面的等价
      validation-query: select '1'
      validation-query-timeout: 1000
      test-on-borrow: false
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 6000000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 6000000
      #filters= #配置多个英文逗号分隔
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath*:/com.fuuzii.*.mapper.*Mapper.xml

